spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/test-person
spring.datasource.username=test_oop2
spring.datasource.password=test_oop2
spring.sql.init.platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
# show SQL queries
spring.jpa.show-sql=true
# set port
server.port=8082

#"id": "5f19b3c1-f898-4204-b178-3f42708b7430" server IT